version: "3.9"
services:
  api:
    build: ./Zeiss.Api
    environment:
      - API_REDISCONNECTIONSTRING=redis
    links:
      - redis
    ports:
      - 5000:80
  ingestor:
    build: ./Zeiss.Ingestor
    environment:
      - INGESTOR_REDISCONNECTIONSTRING=redis
    links:
      - redis
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  redis-data: